### Aptos Vault API 测试
@baseUrl = http://localhost:7001
@investorAddress = 0x125cf356d14b84d866e6698319c6cde798f636b9247fa8078cc3eb860a5c5db3

### 1. 获取特定Aptos Vault信息 (正常)
# @name get_vault_success
GET {{baseUrl}}/aptos/vaults/{{investorAddress}}
Content-Type: application/json

### 2. 获取Aptos Vault操作记录 (正常)
# @name get_vault_operations_success
GET {{baseUrl}}/aptos/vaults/{{investorAddress}}/operations
Content-Type: application/json

### 3. 获取Aptos Vault合约地址 (正常)
# @name get_contract_address_success
GET {{baseUrl}}/aptos/vaults/contract-address
Content-Type: application/json
