### RSSHub节点测试
@baseUrl = http://localhost:7000

### RSSHub节点测试 - 获取CryptoSlate加密货币新闻
# @name execute_rss_listener_node_cryptoslate
POST http://localhost:7000/nodes/execute
Content-Type: application/json

{
  "flow_id": "test_flow",
  "component_id": 0,
  "cycle": 0,
  "node_id": "rss_listener_node_cryptoslate",
  "node_type": "rss_listener_node",
  "name": "RSS Listener Node",
  "edges": [
    {
      "source": "rss_listener_node_cryptoslate",
      "target": "data_processor"
    }
  ],
  "config": {
    "node_class_type": "rss_listener_node",
    "route": "cryptoslate",
    "max_items": 10,
    "include_content": true
  }
}


### RSSHub节点测试 - github
# @name execute_rss_listener_node_cryptoslate
POST http://localhost:7000/nodes/execute
Content-Type: application/json

{
  "flow_id": "test_flow",
  "component_id": 0,
  "cycle": 0,
  "node_id": "rss_listener_node_waite9",
  "node_type": "rss_listener_node",
  "name": "RSS Listener Node",
  "edges": [
    {
      "source": "rss_listener_node_waite9",
      "target": "data_processor"
    }
  ],
  "config": {
    "node_class_type": "rss_listener_node",
    "route": "github/topics/framework",
    "rsshub_url":"https://hub.slarker.me",
    "max_items": 10,
    "include_content": true
  }
}

